image: google/cloud-sdk

pipelines:
  branches:
    devmis:
      - step:
          name: Deploy to GCloud ibrowser-ptest-495
          deployment: test
          script:
          # script code
            - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
            - gcloud auth activate-service-account --key-file gcloud-api-key.json
            - gcloud config set project $GCLOUD_PROJECT
            - gcloud app deploy war/WEB-INF/appengine-web.xml --no-promote  --version test3 --project ibrowser-ptest-495 --verbosity=debug 
            #- gcloud app deploy --version jl-frontend-06 --project ibrowser-ptest-495 --verbosity=debug war/app.yaml